language: swift

os: osx
osx_image: xcode9

xcode_project: Restivus.xcodeproj
xcode_scheme: RestivusTests

cache:
  directories:
    - Carthage

before_install:
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --platform iOS --cache-builds
