language: swift

os: osx
osx_image: xcode9

xcode_scheme: Restivus-iOS
xcode_sdk: iphonesimulator9.3

cache:
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --platform iOS --cache-builds
