language: objective-c

os: osx
osx_image: xcode9
xcode_project: Restivus.xcodeproj
xcode_scheme: RestivusTests
xcode_sdk: iphonesimulator11.0

cache:
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --platform iOS --cache-builds
